{
 "title": "Ruuvi Sensors",
 "tags": [
  "ruuvi",
  "sensors"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Current Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \n  time,\n  \"temperature\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "rawSql": "SELECT \n  time,\n  \"temperature\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "queryText": "SELECT \n  time,\n  \"temperature\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \n  time,\n  \"humidity\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "rawSql": "SELECT \n  time,\n  \"humidity\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "queryText": "SELECT \n  time,\n  \"humidity\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Current Pressure",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \n  time,\n  \"pressure\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "rawSql": "SELECT \n  time,\n  \"pressure\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "queryText": "SELECT \n  time,\n  \"pressure\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Current Battery",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \n  time,\n  \"batteryVoltage\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "rawSql": "SELECT \n  time,\n  \"batteryVoltage\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "queryText": "SELECT \n  time,\n  \"batteryVoltage\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "SELECT \n  time,\n  \"temperature\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "rawSql": "SELECT \n  time,\n  \"temperature\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "queryText": "SELECT \n  time,\n  \"temperature\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT \n  time,\n  \"humidity\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "rawSql": "SELECT \n  time,\n  \"humidity\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "queryText": "SELECT \n  time,\n  \"humidity\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "SELECT \n  time,\n  \"pressure\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "rawSql": "SELECT \n  time,\n  \"pressure\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "queryText": "SELECT \n  time,\n  \"pressure\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "SELECT \n  time,\n  \"batteryVoltage\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "rawSql": "SELECT \n  time,\n  \"batteryVoltage\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "queryText": "SELECT \n  time,\n  \"batteryVoltage\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "SELECT \n  time,\n  \"co2\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "rawSql": "SELECT \n  time,\n  \"co2\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "queryText": "SELECT \n  time,\n  \"co2\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "VOC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "SELECT \n  time,\n  \"voc\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "rawSql": "SELECT \n  time,\n  \"voc\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "queryText": "SELECT \n  time,\n  \"voc\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "PM2.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "µg/m3" } },
   "targets": [
    {
     "query": "SELECT \n  time,\n  \"pm2p5\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "rawSql": "SELECT \n  time,\n  \"pm2p5\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "queryText": "SELECT \n  time,\n  \"pm2p5\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Dew Point",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "SELECT \n  time,\n  \"dewPoint\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "rawSql": "SELECT \n  time,\n  \"dewPoint\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "queryText": "SELECT \n  time,\n  \"dewPoint\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Absolute Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "g/m3" } },
   "targets": [
    {
     "query": "SELECT \n  time,\n  \"absoluteHumidity\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "rawSql": "SELECT \n  time,\n  \"absoluteHumidity\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "queryText": "SELECT \n  time,\n  \"absoluteHumidity\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "SELECT \n  time,\n  \"rssi\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "rawSql": "SELECT \n  time,\n  \"rssi\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC",
     "queryText": "SELECT \n  time,\n  \"rssi\", \"name\"\nFROM \"ruuvi_measurements\"\nWHERE \n  $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  }
 ]
}